### ISSUE TITLE
对于第三方库按需加载的情况如何处理？

### ISSUE THREAD

**Issue by liuyun012** [linpenghui958/postcss-px-to-viewport#2]
对于第三方库按需加载，并且采用的是@vue/cli3 搭建的项目，postcss配置文件写在了 package.json文件里面，应该如何写正则才可以生效？

**Comment by linpenghui958** [comment]
不好意思之前忘记了，最近我会研究一下你说的情况，如果你有解决方案也可以分享一下

**Comment by linpenghui958** [comment]
按需加载的话也是同样定义css文件，单独引入所需的css
